### PR TITLE
Template updated

### PR DESCRIPTION
**Pull request by horberlan**
## Description
- Scroll fixed (it was tripled); general bugs converted; Performance improved considerably; improved user interaction;
- Dependencies are already included;
- I believe that it is only necessary to organize the .css files, which I can do later.

## Type of change

Please tick the relevant option by putting an X inside the bracket

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings
- [x] I have read the [CONTRIBUTING](../CONTRIBUTING.md) document

### CODE REVIEW

**Comment by horberlan** [comment]
@SincerelyFaust  Some of the fixes improve the website's performance, but I'm not sure about the placement of the icons... in react components would be an alternative

**Comment by SincerelyFaust** [comment]
> @SincerelyFaust Some of the fixes improve the website's performance, but I'm not sure about the placement of the icons... in react components would be an alternative

Thank you for this PR, we really appreciate it, but as we've stated before, the #38 pull request will bring an entire rewrite of our website in TypeScript and Next.js,
Your changes will not be able to be merged as they'll either way be overwritten by the PR I mentioned above.
The rewrite should be merged soon so you can take a look again and hopefully we'll be commenting on another PR of yours! :)

**Comment by nmcain** [comment]
We should still continue to maintain in-production software until the end of its lifestyle, especially with the daily amount of traffic our site recieves.

**Comment by nmcain** [comment]
I'm reopening this, because it does improve the website significantly. I'll review the changes.

**Comment by Looskie** [comment]
Hey! #44 was merged, if you have anything you want to carry over from this pr merge master into this, and do the changes you'd like!

as a side note, very sorry for the late response

**Comment by Looskie** [comment]
Closing to clean up PRs

**Pull request closed without merging**
