### PR TITLE
Improve typescript support

### PR DESCRIPTION
**Pull request by etroynov**
## Description

- Improve typescript support

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings
- [x] I have read the [CONTRIBUTING](../CONTRIBUTING.md) document

### CODE REVIEW

**Comment by etroynov** [comment]
@winksaville

**Comment by etroynov** [comment]
@SincerelyFaust

**Comment by larsb24** [comment]
> @SincerelyFaust

@Looskie is the one working on the website. (doesn't make sense pinging Faust, just saying)

**Comment by SincerelyFaust** [comment]
No problems about the ping, thank you for the PR :)

**Review by Looskie — CHANGES_REQUESTED** [review]
Hey, thanks for your contributions but unfortunately we're not really wanting to merge this. There's no real benefit to it, yet it breaks generics, makes children confusing, and has a few other downsides. 

More details here: https://github.com/facebook/create-react-app/pull/8177

However, I do like the fixes with `fontsize` -> `font-size`. 

Hope you're having a good day :)

**Pull request closed without merging**
