### PR TITLE
Update README.md + Dockerize for development

### LINKED ISSUE #33: Add some documentation on how to build and test the website locally
**Is your feature request related to a problem? Please describe.**
I created PR #32 to fix a bug but I couldn't figure out how to build and run the website locally to test the fix.

**Describe the solution you'd like**
Add some documenation ot README.md on how to build and test locally.

**Describe alternatives you've considered**
I don't know of any.

**Do you have an idea of how we would add it?**
If provided the information I will create a PR.

**Why should we add it?**
To make it easier for people to create PR's for the website.

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by winksaville**
Add some instructions for:

 - Install dev tools
   Use yarn v2 instead of the older yarn v1
 - Website layout
   TODO!
 - Local testing
   Basic instructions for testing

This may change significantly after review :)

Fixes #33

## Type of change

Please tick the relevant option by putting an X inside the bracket

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings
- [x] I have read the [CONTRIBUTING](../CONTRIBUTING.md) document

### CODE REVIEW

**Comment by Looskie** [comment]
lgtm! 

in the near future, we're going to be rewriting this entire website in nextjs + ts so the database wont even be needed anymore 🥳 

Is this ready for merge? I do see you have "TODO!" in the description :)

**Comment by Looskie** [comment]
@bleonard252 @nmcain @larsb24 

I've done a little bit chores and dockerized dahlia and added a seeding process. thoughts?

**Comment by winksaville** [comment]
> lgtm!
> 
> in the near future, we're going to be rewriting this entire website in nextjs + ts so the database wont even be needed anymore 
> 
> Is this ready for merge? I do see you have "TODO!" in the description :)

The TODO was just something else I think is needed, otherwise. And as far as nextjs + ts, SGTM, although I was wondering if using flutter + wasm might be a "fun" choice, personally I don't particularly like js. I find ts better, but dahliaos is flutter based and I'd lean in that direction over ts.

Actually, I'm learning rust right now and I'm going to be moving more in that direction from everything I can, so rust + wasm could also be a choice :)

**Comment by winksaville** [comment]
Hmm I tried your `Step 1` but it "failed":
```
$ APP_MODE=SEED yarn devstart
[nodemon] 2.0.7
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node server.js`
/home/wink/prgs/dahliaOS/forks/website/.yarn/cache/mongoose-npm-5.12.3-aa9a3d438c-50e05e1057.zip/node_modules/mongoose/lib/connection.js:694
    throw new MongooseError('The `uri` parameter to `openUri()` must be a ' +
    ^

MongooseError: The `uri` parameter to `openUri()` must be a string, got "undefined". Make sure the first parameter to `mongoose.connect()` or `mongoose.createConnection()` is a string.
    at NativeConnection.Connection.openUri (/home/wink/prgs/dahliaOS/forks/website/.yarn/cache/mongoose-npm-5.12.3-aa9a3d438c-50e05e1057.zip/node_modules/mongoose/lib/connection.js:694:11)
    at /home/wink/prgs/dahliaOS/forks/website/.yarn/cache/mongoose-npm-5.12.3-aa9a3d438c-50e05e1057.zip/node_modules/mongoose/lib/index.js:348:10
    at promiseOrCallback (/home/wink/prgs/dahliaOS/forks/website/.yarn/cache/mongoose-npm-5.12.3-aa9a3d438c-50e05e1057.zip/node_modules/mongoose/lib/helpers/promiseOrCallback.js:9:12)
    at Mongoose._promiseOrCallback (/home/wink/prgs/dahliaOS/forks/website/.yarn/cache/mongoose-npm-5.12.3-aa9a3d438c-50e05e1057.zip/node_modules/mongoose/lib/index.js:1152:10)
    at Mongoose.connect (/home/wink/prgs/dahliaOS/forks/website/.yarn/cache/mongoose-npm-5.12.3-aa9a3d438c-50e05e1057.zip/node_modules/mongoose/lib/index.js:347:20)
    at Object.<anonymous> (/home/wink/prgs/dahliaOS/forks/website/server.js:17:10)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Module.load (node:internal/modules/cjs/loader:989:32)
    at Function.external_module_.Module._load (/home/wink/prgs/dahliaOS/forks/website/.pnp.js:8238:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47
[nodemon] app crashed - waiting for file changes before starting...
```

It behaves better if I also add "DB_URL":
```
wink@3900x:~/prgs/dahliaOS/forks/website (Update-README.md)
$ APP_MODE=SEED DB_URL=mongodb://localhost yarn devstart
[nodemon] 2.0.7
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node server.js`
express-session deprecated req.secret; provide secret option server.js:49:3
listening on port 3000
```

But I'm not sure that is correct either?

Also the rendered README doesn't look right:

Screenshot from 2021-06-09 16-02-29

**Comment by Looskie** [comment]
> > lgtm!
> > in the near future, we're going to be rewriting this entire website in nextjs + ts so the database wont even be needed anymore
> > Is this ready for merge? I do see you have "TODO!" in the description :)
> 
> The TODO was just something else I think is needed, otherwise. And as far as nextjs + ts, SGTM, although I was wondering if using flutter + wasm might be a "fun" choice, personally I don't particularly like js. I find ts better, but dahliaos is flutter based and I'd lean in that direction over ts.
> 
> Actually, I'm learning rust right now and I'm going to be moving more in that direction from everything I can, so rust + wasm could also be a choice :)

The entire reason I want to move the website to NextJS is because its INSANELY fast, Like we're talking sub 50ms fast for each page. It would be GREAT for user experience and documentation. 


As for the error for the URI, what is your ENV file for the database?

**Comment by Looskie** [comment]
Furthermore, you can change the readme as you want, i just added it as a boiler for now so we don't forget to tell people to seed on their first start.

**Comment by winksaville** [comment]
> Furthermore, you can change the readme as you want, i just added it as a boiler for now so we don't forget to tell people to seed on their first start.

Ok, I'll tweak the README.

I don't have an environment file for the database, which is probably the problem! Can you provide a link to a short tutorial on how to setup the DB env, I'll include that link or a short synopsis if possible. Or maybe we can just include an quick and dirty initial enviornemt and a link on how to customize it?

On the other hand it seems all of the content is static and people aren't logging in so why is there a need for the a database in the firstplace?

Oh, and I hope your finals go well, its been a loooooong time since I was in HS, LoL!

**Comment by Looskie** [comment]
> > Furthermore, you can change the readme as you want, i just added it as a boiler for now so we don't forget to tell people to seed on their first start.
> 
> Ok, I'll tweak the README.
> 
> I don't have an environment file for the database, which is probably the problem! Can you provide a link to a short tutorial on how to setup the DB env, I'll include that link or a short synopsis if possible. Or maybe we can just include an quick and dirty initial enviornemt and a link on how to customize it?
> 
> On the other hand it seems all of the content is static and people aren't logging in so why is there a need for the a database in the firstplace?
> 
> Oh, and I hope your finals go well, its been a loooooong time since I was in HS, LoL!

Creating the env stuff is deaddd simple, in the commits, you should have a `.env-example`, rename that to `.env` and start the server, i set the examples to be pretty much plug and play! 

And thank youu! Appreciate the luck ❤️

**Comment by winksaville** [comment]
Using the `.env-example` worked like a charm! Made a couple tweaks to the README.md.

**Comment by Looskie** [comment]
Great! So we're all set for merge right?

**Review by Looskie — APPROVED** [review]
LGTM

**Comment by winksaville** [comment]
LGTMT

**Comment by Looskie** [comment]
Thank you for everything! ❤️

**Comment by bleonard252** [comment]
ngl it's kinda rude to remove reviews from people @Looskie

**Comment by Looskie** [comment]
> ngl it's kinda rude to remove reviews from people @Looskie 

😩😩😩😩 my fault @bleonard252

**Pull request merged**
